### ISSUE TITLE
Don't understand how to install Python bindings

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [neXyon/audaspace#38]
The configure script checks for appropriate Python ...

```
Found PythonInterp: /usr/bin/python3 (found suitable version "3.10.4", minimum required is
 "3.2")
 Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found suitable version "3.10.4",
 minimum required is "3.2")
```
Yet the bindings library appears to be a deprecated egg type ?

Testing with ...

```
#!/usr/bin/python
import aud, time
```

Shows ...

```
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ ./aud-test.py 
Traceback (most recent call last):
  File "/home/michaelzfreeman/./aud-test.py", line 2, in <module>
    import aud, time
ImportError: libaudaspace.so.1.3: cannot open shared object file: No such file or directory
```
Attempting to install with pip gives ...

```
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ pip install aud
Defaulting to user installation because normal site-packages is not writeable
Collecting aud
  Downloading aud-0.8.6.tar.gz (9.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-c75z8jjl/aud_55c72a661d7f4c3c8e95bee6b85b59f3/setup.py", line 4, in <module>
          from m2r import parse_from_file
      ModuleNotFoundError: No module named 'm2r'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ pip install m2r
Defaulting to user installation because normal site-packages is not writeable
Collecting m2r
  Downloading m2r-0.2.1.tar.gz (16 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: docutils in ./.local/lib/python3.10/site-packages (from m2r) (0.19)
Collecting mistune
  Downloading mistune-2.0.4-py2.py3-none-any.whl (24 kB)
Building wheels for collected packages: m2r
  Building wheel for m2r (setup.py) ... done
  Created wheel for m2r: filename=m2r-0.2.1-py3-none-any.whl size=10477 sha256=b8f961d30f0c24343dc4ec6daf53b2d659067fbc9ba23e97a8e469a52f33a387
  Stored in directory: /home/michaelzfreeman/.cache/pip/wheels/61/4f/0e/b738b796091ddefde08f9731e537eade93b866f5f1e7963f48
Successfully built m2r
Installing collected packages: mistune, m2r
  WARNING: The script m2r is installed in '/home/michaelzfreeman/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed m2r-0.2.1 mistune-2.0.4
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ vim .bashrc

[3]+  Stopped                 vim .bashrc
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ fg
vim .bashrc

[3]+  Stopped                 vim .bashrc
michaelzfreeman@michaelzfreeman-Swift-SF113-31-Kubuntu
~
$ pip install aud
Defaulting to user installation because normal site-packages is not writeable
Collecting aud
  Using cached aud-0.8.6.tar.gz (9.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-dn197zl1/aud_db377363814549b687b7535e5419846a/setup.py", line 4, in <module>
          from m2r import parse_from_file
        File "/home/michaelzfreeman/.local/lib/python3.10/site-packages/m2r.py", line 13, in <module>
          from docutils.core import ErrorString
      ImportError: cannot import name 'ErrorString' from 'docutils.core' (/home/michaelzfreeman/.local/lib/python3.10/site-packages/docutils/core.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by neXyon** [comment]
The ImportError shows that it cannot find Audaspace's shared libraries, where did you install those to and is this path part of your `LD_LIBRARY_PATH`? You should set a proper `CMAKE_INSTALL_PREFIX` in cmake, i.e. one where `$CMAKE_INSTALL_PREFIX/lib` is contained in your system's `LD_LIBRABRY_PATH`. Typically that is `/usr` or `/usr/local`. See for example the build and package steps here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=audaspace-git

The aud you tried to install with pip is something completely different: https://pypi.org/project/aud/
